### ISSUE TITLE
`make apply` fails due to missing allowed_account_ids config stanza

### ISSUE THREAD

**Issue by trevoro** [commitdev/commit0#104]
When executing against the staging environment

```
Error: Missing required argument

  on main.tf line 13, in module "staging":
  13: module "staging" {

The argument "allowed_account_ids" is required, but no definition was found.

make: *** [apply-env] Error 1
```

uncommenting the line in the config makes it work.
It's not clear why the line is commented out.

**Comment by zthomas** [comment]
Oh yes, that was my bad, I actually caught that earlier in the Carmodity demo. I'll fix that. Before we had a module parameter that would have prompted the user for the accountID. I'll submit a PR
