### ISSUE TITLE
Generate circle ci / other ci manifests

### ISSUE THREAD

**Issue by Pritesh-Patel** [commitdev/commit0#2]

**Comment by Direside** [comment]
I can work on this one for you if you like. I'll have some time this weekend.

**Comment by Pritesh-Patel** [comment]
Awesome! Feel free to assign it to yourself - when you want to take it on 😃

**Comment by jb55** [comment]
I can get this started if that's cool

**Comment by Direside** [comment]
@jb55 I've already started work on this one. Sorry I missed your comment. It's on the branch ` 2-generate-ci-manifests` if you want to take a look.

**Comment by jb55** [comment]
Shane Gearon <notifications@github.com> writes:

> @jb55 I've already started work on this one. Sorry I missed your
> comment. It's on the branch ` 2-generate-ci-manifests` if you want to
> take a look.

ah ok cool I won't step on your toes but I'll take a look

-- 
https://jb55.com
