### ISSUE TITLE
Configuration UI for commit0.yml

### ISSUE THREAD

**Issue by Direside** [commitdev/commit0#56]
Add a new command `commit0 start` (or a better name if you know one) that will serve up a single webpage that has a UI to select all the different options you can configure with your app.

### Acceptance Criteria:
- All the current options in the commit0.yml are listed
- You can switch between the options E.g. True/False radio buttons, multi-select is dropdown, etc.
- Website generates a yaml output to the browser that can be copied and have the command line tool run against it

**Comment by liang-lillian** [comment]
last AC to be updated to - website calls post endpoint (generate_api)
