### ISSUE TITLE
CircleCI config running and authenticated to start running the pipeline

### ISSUE THREAD

**Issue by Direside** [commitdev/commit0#58]
We need to find a way to either via the UI or APIs, have the CircleCI pipeline fully set up and running.

### Acceptance Criteria:
- When projects are generated they request all the required permissions to enable circleci for your project
- Project is enabled on CircleCI
- Documentation for any manual steps that cannot be avoided

**Comment by zthomas** [comment]
We are focusing on Github Actions for now.
