### ISSUE TITLE
Explore way of visualising the infrastructure

### ISSUE THREAD

**Issue by zthomas** [commitdev/commit0#80]
Are there any good existing solutions that can easily draw out an infrastructure diagram automatically?

Automated Solutions: 
https://www.mapbox.com/solutions/asset-tracking
https://cloudcraft.co/
https://www.terraform.io/docs/commands/graph.html

Diagram Products:
https://creately.com/lp/draw-aws-diagrams-online/
https://www.lucidchart.com/blog/network-infrastructure-mapping

**Comment by ShahNewazKhan** [comment]
https://github.com/28mm/blast-radius
